on:
  workflow_dispatch:
    inputs:
      dry-run:
        default: true
        description: Dry-Run
        required: false
        type: boolean

name: publish

jobs:
  publish:
    permissions: read-all
    uses: mxenabled/path-tools/.github/workflows/publish.yml@master
    with:
      dry-run: ${{ inputs.dry-run }}
    secrets:
      OSSRH_USERNAME: bob
      OSSRH_TOKEN: asdf
      GPG_SIGNING_KEY_BASE64: afefdf
      GPG_SIGNING_PASSPHRASE: h24o9fhuh
