on:
  workflow_dispatch:
  push:
    branches:
      - master
      - rc

name: release

jobs:
  release:
    permissions: write-all
    uses: mxenabled/path-tools/.github/workflows/release_semantic.yml@master
    with:
      dry-run: false
    secrets:
      SEMANTIC_TOKEN: ${{ secrets.SEMANTIC_TOKEN }}
      OSSRH_USERNAME: bob
      OSSRH_TOKEN: asdf
      GPG_SIGNING_KEY_BASE64: afefdf
      GPG_SIGNING_PASSPHRASE: h24o9fhuh
