on:
  workflow_dispatch:
  push:
    branches:
      - master

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: mxenabled/path-tools/.github/workflows/release.yml@master
