on:
  workflow_dispatch:
  push:
    branches:
      - master

name: release

jobs:
  release:
    permissions: write-all
    uses: mxenabled/path-tools/.github/workflows/release.yml@master
    with:
      dry-run: true
    secrets:
      OSSRH_USERNAME: bob
      OSSRH_TOKEN: asdf
      GPG_SIGNING_KEY_BASE64: afefdf
      GPG_SIGNING_PASSPHRASE: h24o9fhuh
