on:
  workflow_dispatch:
  push:
    branches:
      - master
      - rc

name: release

jobs:
  release:
    permissions: write-all
    uses: mxenabled/path-tools/.github/workflows/release_semantic.yml@ts
    with:
      dry-run: false
    secrets:
      SEMANTIC_TOKEN: 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
      OSSRH_USERNAME: bob
      OSSRH_TOKEN: asdf
      GPG_SIGNING_KEY_BASE64: afefdf
      GPG_SIGNING_PASSPHRASE: h24o9fhuh
