on:
  push:

name: release

jobs:
  # ---------------------------------------------------------------
  # job: release
  #
  # Run release-please and publish the release if release-please
  # creates a release.
  #
  # * Creates and maintains "release PR"
  # * Creates release when the "release PR" is merged to "master"
  # * Publishes release if release-please creates a release
  #
  # See: https://github.com/google-github-actions/release-please-action
  # See: https://github.com/googleapis/release-please
  #
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.repository }}
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3.5.0
        id: release
        with:
          command: manifest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

  publish:
    needs: [ release ]
    # runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.release_created }}
    uses: mxenabled/path-tools/.github/workflows/publish.yml@master
    with:
      dry-run: true
    secrets:
      OSSRH_USERNAME: not_published
      OSSRH_TOKEN: not_published
      GPG_SIGNING_KEY_BASE64: not_published
      GPG_SIGNING_PASSPHRASE: not_published
