on:
  push:
    branches:
      - master

  workflow_call:
    inputs:
      dry-run:
        default: false
        description: Only publish locally
        required: false
        type: boolean
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_TOKEN:
        required: true
      GPG_SIGNING_KEY_BASE64:
        required: true
      GPG_SIGNING_PASSPHRASE:
        required: true

name: release

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install -g commitlint@latest @commitlint/config-conventional semantic-release @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator @google/semantic-release-replace-plugin @semantic-release/changelog conventional-changelog-conventionalcommits
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          tag_format: ${version}
          extra_plugins: |
            commitlint@latest 
            @commitlint/config-conventional
            semantic-release
            @semantic-release/git
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @google/semantic-release-replace-plugin
            @semantic-release/changelog
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Setup Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "lts/*"
      # - name: Install dependencies
      #   run: npm install -g commitlint@latest @commitlint/config-conventional semantic-release @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator @google/semantic-release-replace-plugin @semantic-release/changelog conventional-changelog-conventionalcommits
      # - if: ${{ inputs.dry-run }}
      #   name: Release (dry-run)
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npx semantic-release --dryRun
      # - if: ${{ !inputs.dry-run }}
      #   name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npx semantic-release
